name: user_command_example
description: "An example of the user_command flutter library"
publish_to: 'none'
git initversion: 0.1.0

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  user_command:
    path: ../user_command

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
